//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalWinForm.Fissal.WSExternos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CredencialServicio", Namespace="http://schemas.datacontract.org/2004/07/FissalSWSExternos")]
    [System.SerializableAttribute()]
    public partial class CredencialServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/FissalSWSExternos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FissalWinForm.Fissal.WSExternos.PacienteRespuesta))]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteRespuesta", Namespace="http://schemas.datacontract.org/2004/07/FissalSWSExternos")]
    [System.SerializableAttribute()]
    public partial class PacienteRespuesta : FissalWinForm.Fissal.WSExternos.Respuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FissalWinForm.Fissal.WSExternos.AutorizacionWS> AutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FissalWinForm.Fissal.WSExternos.Paciente PacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FissalWinForm.Fissal.WSExternos.PacienteWS> PacientesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FissalWinForm.Fissal.WSExternos.AutorizacionWS> Autorizacion {
            get {
                return this.AutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizacionField, value) != true)) {
                    this.AutorizacionField = value;
                    this.RaisePropertyChanged("Autorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FissalWinForm.Fissal.WSExternos.Paciente Paciente {
            get {
                return this.PacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteField, value) != true)) {
                    this.PacienteField = value;
                    this.RaisePropertyChanged("Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FissalWinForm.Fissal.WSExternos.PacienteWS> Pacientes {
            get {
                return this.PacientesField;
            }
            set {
                if ((object.ReferenceEquals(this.PacientesField, value) != true)) {
                    this.PacientesField = value;
                    this.RaisePropertyChanged("Pacientes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://schemas.datacontract.org/2004/07/FissalSWSExternos")]
    [System.SerializableAttribute()]
    public partial class Paciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FissalWinForm.Fissal.WSExternos.Autorizacion> AutorizacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstablecimientoIdOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtrosNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SexoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> TipoDocumentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TipoRegimenIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ubigeo_AdscripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ubigeo_ResidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fecha_defuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_contratoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FissalWinForm.Fissal.WSExternos.Autorizacion> Autorizaciones {
            get {
                return this.AutorizacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizacionesField, value) != true)) {
                    this.AutorizacionesField = value;
                    this.RaisePropertyChanged("Autorizaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstablecimientoIdOrigen {
            get {
                return this.EstablecimientoIdOrigenField;
            }
            set {
                if ((this.EstablecimientoIdOrigenField.Equals(value) != true)) {
                    this.EstablecimientoIdOrigenField = value;
                    this.RaisePropertyChanged("EstablecimientoIdOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Historia {
            get {
                return this.HistoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoriaField, value) != true)) {
                    this.HistoriaField = value;
                    this.RaisePropertyChanged("Historia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Nacimiento {
            get {
                return this.NacimientoField;
            }
            set {
                if ((this.NacimientoField.Equals(value) != true)) {
                    this.NacimientoField = value;
                    this.RaisePropertyChanged("Nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtrosNombres {
            get {
                return this.OtrosNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.OtrosNombresField, value) != true)) {
                    this.OtrosNombresField = value;
                    this.RaisePropertyChanged("OtrosNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteId {
            get {
                return this.PacienteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteIdField, value) != true)) {
                    this.PacienteIdField = value;
                    this.RaisePropertyChanged("PacienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SexoId {
            get {
                return this.SexoIdField;
            }
            set {
                if ((this.SexoIdField.Equals(value) != true)) {
                    this.SexoIdField = value;
                    this.RaisePropertyChanged("SexoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> TipoDocumentoId {
            get {
                return this.TipoDocumentoIdField;
            }
            set {
                if ((this.TipoDocumentoIdField.Equals(value) != true)) {
                    this.TipoDocumentoIdField = value;
                    this.RaisePropertyChanged("TipoDocumentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TipoRegimenId {
            get {
                return this.TipoRegimenIdField;
            }
            set {
                if ((this.TipoRegimenIdField.Equals(value) != true)) {
                    this.TipoRegimenIdField = value;
                    this.RaisePropertyChanged("TipoRegimenId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubigeo_Adscripcion {
            get {
                return this.Ubigeo_AdscripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.Ubigeo_AdscripcionField, value) != true)) {
                    this.Ubigeo_AdscripcionField = value;
                    this.RaisePropertyChanged("Ubigeo_Adscripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubigeo_Residencia {
            get {
                return this.Ubigeo_ResidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.Ubigeo_ResidenciaField, value) != true)) {
                    this.Ubigeo_ResidenciaField = value;
                    this.RaisePropertyChanged("Ubigeo_Residencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCreacion {
            get {
                return this.UsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreacionField, value) != true)) {
                    this.UsuarioCreacionField = value;
                    this.RaisePropertyChanged("UsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Validado {
            get {
                return this.ValidadoField;
            }
            set {
                if ((this.ValidadoField.Equals(value) != true)) {
                    this.ValidadoField = value;
                    this.RaisePropertyChanged("Validado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha_defuncion {
            get {
                return this.fecha_defuncionField;
            }
            set {
                if ((this.fecha_defuncionField.Equals(value) != true)) {
                    this.fecha_defuncionField = value;
                    this.RaisePropertyChanged("fecha_defuncion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nro_contrato {
            get {
                return this.nro_contratoField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_contratoField, value) != true)) {
                    this.nro_contratoField = value;
                    this.RaisePropertyChanged("nro_contrato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorizacionWS", Namespace="http://schemas.datacontract.org/2004/07/FissalSWSExternos")]
    [System.SerializableAttribute()]
    public partial class AutorizacionWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdicionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutorizacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ControlaCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiagnosticoAsociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstablecimientoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nro_SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PreAutorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TipoAutorizacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TratamiendoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VigenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Adicional {
            get {
                return this.AdicionalField;
            }
            set {
                if ((this.AdicionalField.Equals(value) != true)) {
                    this.AdicionalField = value;
                    this.RaisePropertyChanged("Adicional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anulado {
            get {
                return this.AnuladoField;
            }
            set {
                if ((this.AnuladoField.Equals(value) != true)) {
                    this.AnuladoField = value;
                    this.RaisePropertyChanged("Anulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutorizacionId {
            get {
                return this.AutorizacionIdField;
            }
            set {
                if ((this.AutorizacionIdField.Equals(value) != true)) {
                    this.AutorizacionIdField = value;
                    this.RaisePropertyChanged("AutorizacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAutorizacion {
            get {
                return this.CodigoAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAutorizacionField, value) != true)) {
                    this.CodigoAutorizacionField = value;
                    this.RaisePropertyChanged("CodigoAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ControlaCantidad {
            get {
                return this.ControlaCantidadField;
            }
            set {
                if ((this.ControlaCantidadField.Equals(value) != true)) {
                    this.ControlaCantidadField = value;
                    this.RaisePropertyChanged("ControlaCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DiagnosticoAsociado {
            get {
                return this.DiagnosticoAsociadoField;
            }
            set {
                if ((this.DiagnosticoAsociadoField.Equals(value) != true)) {
                    this.DiagnosticoAsociadoField = value;
                    this.RaisePropertyChanged("DiagnosticoAsociado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstablecimientoId {
            get {
                return this.EstablecimientoIdField;
            }
            set {
                if ((this.EstablecimientoIdField.Equals(value) != true)) {
                    this.EstablecimientoIdField = value;
                    this.RaisePropertyChanged("EstablecimientoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaSolicitud {
            get {
                return this.FechaSolicitudField;
            }
            set {
                if ((this.FechaSolicitudField.Equals(value) != true)) {
                    this.FechaSolicitudField = value;
                    this.RaisePropertyChanged("FechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modalidad {
            get {
                return this.ModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalidadField, value) != true)) {
                    this.ModalidadField = value;
                    this.RaisePropertyChanged("Modalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nro_Solicitud {
            get {
                return this.Nro_SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.Nro_SolicitudField, value) != true)) {
                    this.Nro_SolicitudField = value;
                    this.RaisePropertyChanged("Nro_Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteId {
            get {
                return this.PacienteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteIdField, value) != true)) {
                    this.PacienteIdField = value;
                    this.RaisePropertyChanged("PacienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PreAutorizado {
            get {
                return this.PreAutorizadoField;
            }
            set {
                if ((this.PreAutorizadoField.Equals(value) != true)) {
                    this.PreAutorizadoField = value;
                    this.RaisePropertyChanged("PreAutorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TipoAutorizacionId {
            get {
                return this.TipoAutorizacionIdField;
            }
            set {
                if ((this.TipoAutorizacionIdField.Equals(value) != true)) {
                    this.TipoAutorizacionIdField = value;
                    this.RaisePropertyChanged("TipoAutorizacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TratamiendoId {
            get {
                return this.TratamiendoIdField;
            }
            set {
                if ((this.TratamiendoIdField.Equals(value) != true)) {
                    this.TratamiendoIdField = value;
                    this.RaisePropertyChanged("TratamiendoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCreacion {
            get {
                return this.UsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreacionField, value) != true)) {
                    this.UsuarioCreacionField = value;
                    this.RaisePropertyChanged("UsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Vigencia {
            get {
                return this.VigenciaField;
            }
            set {
                if ((this.VigenciaField.Equals(value) != true)) {
                    this.VigenciaField = value;
                    this.RaisePropertyChanged("Vigencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteWS", Namespace="http://schemas.datacontract.org/2004/07/FissalSWSExternos")]
    [System.SerializableAttribute()]
    public partial class PacienteWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtrosNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SexoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> TipoDocumentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TipoRegimenIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Historia {
            get {
                return this.HistoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoriaField, value) != true)) {
                    this.HistoriaField = value;
                    this.RaisePropertyChanged("Historia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Nacimiento {
            get {
                return this.NacimientoField;
            }
            set {
                if ((this.NacimientoField.Equals(value) != true)) {
                    this.NacimientoField = value;
                    this.RaisePropertyChanged("Nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtrosNombres {
            get {
                return this.OtrosNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.OtrosNombresField, value) != true)) {
                    this.OtrosNombresField = value;
                    this.RaisePropertyChanged("OtrosNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteId {
            get {
                return this.PacienteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteIdField, value) != true)) {
                    this.PacienteIdField = value;
                    this.RaisePropertyChanged("PacienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SexoId {
            get {
                return this.SexoIdField;
            }
            set {
                if ((this.SexoIdField.Equals(value) != true)) {
                    this.SexoIdField = value;
                    this.RaisePropertyChanged("SexoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> TipoDocumentoId {
            get {
                return this.TipoDocumentoIdField;
            }
            set {
                if ((this.TipoDocumentoIdField.Equals(value) != true)) {
                    this.TipoDocumentoIdField = value;
                    this.RaisePropertyChanged("TipoDocumentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TipoRegimenId {
            get {
                return this.TipoRegimenIdField;
            }
            set {
                if ((this.TipoRegimenIdField.Equals(value) != true)) {
                    this.TipoRegimenIdField = value;
                    this.RaisePropertyChanged("TipoRegimenId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autorizacion", Namespace="http://schemas.datacontract.org/2004/07/FissalSWSExternos")]
    [System.SerializableAttribute()]
    public partial class Autorizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdicionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutorizacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ControlaCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiagnosticoAsociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstablecimientoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInformeMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nro_SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PreAutorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TipoAutorizacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TratamiendoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VigenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Adicional {
            get {
                return this.AdicionalField;
            }
            set {
                if ((this.AdicionalField.Equals(value) != true)) {
                    this.AdicionalField = value;
                    this.RaisePropertyChanged("Adicional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anulado {
            get {
                return this.AnuladoField;
            }
            set {
                if ((this.AnuladoField.Equals(value) != true)) {
                    this.AnuladoField = value;
                    this.RaisePropertyChanged("Anulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutorizacionId {
            get {
                return this.AutorizacionIdField;
            }
            set {
                if ((this.AutorizacionIdField.Equals(value) != true)) {
                    this.AutorizacionIdField = value;
                    this.RaisePropertyChanged("AutorizacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAutorizacion {
            get {
                return this.CodigoAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAutorizacionField, value) != true)) {
                    this.CodigoAutorizacionField = value;
                    this.RaisePropertyChanged("CodigoAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ControlaCantidad {
            get {
                return this.ControlaCantidadField;
            }
            set {
                if ((this.ControlaCantidadField.Equals(value) != true)) {
                    this.ControlaCantidadField = value;
                    this.RaisePropertyChanged("ControlaCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DiagnosticoAsociado {
            get {
                return this.DiagnosticoAsociadoField;
            }
            set {
                if ((this.DiagnosticoAsociadoField.Equals(value) != true)) {
                    this.DiagnosticoAsociadoField = value;
                    this.RaisePropertyChanged("DiagnosticoAsociado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enviado {
            get {
                return this.EnviadoField;
            }
            set {
                if ((this.EnviadoField.Equals(value) != true)) {
                    this.EnviadoField = value;
                    this.RaisePropertyChanged("Enviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstablecimientoId {
            get {
                return this.EstablecimientoIdField;
            }
            set {
                if ((this.EstablecimientoIdField.Equals(value) != true)) {
                    this.EstablecimientoIdField = value;
                    this.RaisePropertyChanged("EstablecimientoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInformeMedico {
            get {
                return this.FechaInformeMedicoField;
            }
            set {
                if ((this.FechaInformeMedicoField.Equals(value) != true)) {
                    this.FechaInformeMedicoField = value;
                    this.RaisePropertyChanged("FechaInformeMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRespuesta {
            get {
                return this.FechaRespuestaField;
            }
            set {
                if ((this.FechaRespuestaField.Equals(value) != true)) {
                    this.FechaRespuestaField = value;
                    this.RaisePropertyChanged("FechaRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaSolicitud {
            get {
                return this.FechaSolicitudField;
            }
            set {
                if ((this.FechaSolicitudField.Equals(value) != true)) {
                    this.FechaSolicitudField = value;
                    this.RaisePropertyChanged("FechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modalidad {
            get {
                return this.ModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalidadField, value) != true)) {
                    this.ModalidadField = value;
                    this.RaisePropertyChanged("Modalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nro_Solicitud {
            get {
                return this.Nro_SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.Nro_SolicitudField, value) != true)) {
                    this.Nro_SolicitudField = value;
                    this.RaisePropertyChanged("Nro_Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteId {
            get {
                return this.PacienteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteIdField, value) != true)) {
                    this.PacienteIdField = value;
                    this.RaisePropertyChanged("PacienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PreAutorizado {
            get {
                return this.PreAutorizadoField;
            }
            set {
                if ((this.PreAutorizadoField.Equals(value) != true)) {
                    this.PreAutorizadoField = value;
                    this.RaisePropertyChanged("PreAutorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TipoAutorizacionId {
            get {
                return this.TipoAutorizacionIdField;
            }
            set {
                if ((this.TipoAutorizacionIdField.Equals(value) != true)) {
                    this.TipoAutorizacionIdField = value;
                    this.RaisePropertyChanged("TipoAutorizacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TratamiendoId {
            get {
                return this.TratamiendoIdField;
            }
            set {
                if ((this.TratamiendoIdField.Equals(value) != true)) {
                    this.TratamiendoIdField = value;
                    this.RaisePropertyChanged("TratamiendoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCreacion {
            get {
                return this.UsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCreacionField, value) != true)) {
                    this.UsuarioCreacionField = value;
                    this.RaisePropertyChanged("UsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Vigencia {
            get {
                return this.VigenciaField;
            }
            set {
                if ((this.VigenciaField.Equals(value) != true)) {
                    this.VigenciaField = value;
                    this.RaisePropertyChanged("Vigencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fissal.gob.pe/wspaciente/", ConfigurationName="Fissal.WSExternos.IPacienteService")]
    public interface IPacienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fissal.gob.pe/wspaciente/IPacienteService/ConsultarPaciente", ReplyAction="http://fissal.gob.pe/wspaciente/IPacienteService/ConsultarPacienteResponse")]
        FissalWinForm.Fissal.WSExternos.PacienteRespuesta ConsultarPaciente(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int tipoDocumentoId, string numeroDocumento, int establecimientoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fissal.gob.pe/wspaciente/IPacienteService/ConsultarPaciente", ReplyAction="http://fissal.gob.pe/wspaciente/IPacienteService/ConsultarPacienteResponse")]
        System.Threading.Tasks.Task<FissalWinForm.Fissal.WSExternos.PacienteRespuesta> ConsultarPacienteAsync(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int tipoDocumentoId, string numeroDocumento, int establecimientoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fissal.gob.pe/wspaciente/IPacienteService/ObtenerPacientes", ReplyAction="http://fissal.gob.pe/wspaciente/IPacienteService/ObtenerPacientesResponse")]
        FissalWinForm.Fissal.WSExternos.PacienteRespuesta ObtenerPacientes(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int establecimientoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fissal.gob.pe/wspaciente/IPacienteService/ObtenerPacientes", ReplyAction="http://fissal.gob.pe/wspaciente/IPacienteService/ObtenerPacientesResponse")]
        System.Threading.Tasks.Task<FissalWinForm.Fissal.WSExternos.PacienteRespuesta> ObtenerPacientesAsync(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int establecimientoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fissal.gob.pe/wspaciente/IPacienteService/ActualizarAutorizaciones", ReplyAction="http://fissal.gob.pe/wspaciente/IPacienteService/ActualizarAutorizacionesResponse" +
            "")]
        string ActualizarAutorizaciones(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, System.Collections.Generic.List<int> autorizaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fissal.gob.pe/wspaciente/IPacienteService/ActualizarAutorizaciones", ReplyAction="http://fissal.gob.pe/wspaciente/IPacienteService/ActualizarAutorizacionesResponse" +
            "")]
        System.Threading.Tasks.Task<string> ActualizarAutorizacionesAsync(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, System.Collections.Generic.List<int> autorizaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fissal.gob.pe/wspaciente/IPacienteService/ObtenerAutorizaciones", ReplyAction="http://fissal.gob.pe/wspaciente/IPacienteService/ObtenerAutorizacionesResponse")]
        FissalWinForm.Fissal.WSExternos.PacienteRespuesta ObtenerAutorizaciones(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int establecimientoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fissal.gob.pe/wspaciente/IPacienteService/ObtenerAutorizaciones", ReplyAction="http://fissal.gob.pe/wspaciente/IPacienteService/ObtenerAutorizacionesResponse")]
        System.Threading.Tasks.Task<FissalWinForm.Fissal.WSExternos.PacienteRespuesta> ObtenerAutorizacionesAsync(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int establecimientoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPacienteServiceChannel : FissalWinForm.Fissal.WSExternos.IPacienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PacienteServiceClient : System.ServiceModel.ClientBase<FissalWinForm.Fissal.WSExternos.IPacienteService>, FissalWinForm.Fissal.WSExternos.IPacienteService {
        
        public PacienteServiceClient() {
        }
        
        public PacienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PacienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FissalWinForm.Fissal.WSExternos.PacienteRespuesta ConsultarPaciente(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int tipoDocumentoId, string numeroDocumento, int establecimientoId) {
            return base.Channel.ConsultarPaciente(credencial, tipoDocumentoId, numeroDocumento, establecimientoId);
        }
        
        public System.Threading.Tasks.Task<FissalWinForm.Fissal.WSExternos.PacienteRespuesta> ConsultarPacienteAsync(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int tipoDocumentoId, string numeroDocumento, int establecimientoId) {
            return base.Channel.ConsultarPacienteAsync(credencial, tipoDocumentoId, numeroDocumento, establecimientoId);
        }
        
        public FissalWinForm.Fissal.WSExternos.PacienteRespuesta ObtenerPacientes(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int establecimientoId) {
            return base.Channel.ObtenerPacientes(credencial, establecimientoId);
        }
        
        public System.Threading.Tasks.Task<FissalWinForm.Fissal.WSExternos.PacienteRespuesta> ObtenerPacientesAsync(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int establecimientoId) {
            return base.Channel.ObtenerPacientesAsync(credencial, establecimientoId);
        }
        
        public string ActualizarAutorizaciones(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, System.Collections.Generic.List<int> autorizaciones) {
            return base.Channel.ActualizarAutorizaciones(credencial, autorizaciones);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarAutorizacionesAsync(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, System.Collections.Generic.List<int> autorizaciones) {
            return base.Channel.ActualizarAutorizacionesAsync(credencial, autorizaciones);
        }
        
        public FissalWinForm.Fissal.WSExternos.PacienteRespuesta ObtenerAutorizaciones(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int establecimientoId) {
            return base.Channel.ObtenerAutorizaciones(credencial, establecimientoId);
        }
        
        public System.Threading.Tasks.Task<FissalWinForm.Fissal.WSExternos.PacienteRespuesta> ObtenerAutorizacionesAsync(FissalWinForm.Fissal.WSExternos.CredencialServicio credencial, int establecimientoId) {
            return base.Channel.ObtenerAutorizacionesAsync(credencial, establecimientoId);
        }
    }
}
