//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalWebForm.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sis.gob.pe/", ConfigurationName="ServiceReference1.siswsSoap")]
    public interface siswsSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje BuscarAseguradosDocIdentRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAseguradosDocIdent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentResponse BuscarAseguradosDocIdent(FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAseguradosDocIdent", ReplyAction="*")]
        System.Threading.Tasks.Task<FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentResponse> BuscarAseguradosDocIdentAsync(FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje BuscarDNI_BRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarDNI_B", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FissalWebForm.ServiceReference1.BuscarDNI_BResponse BuscarDNI_B(FissalWebForm.ServiceReference1.BuscarDNI_BRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarDNI_B", ReplyAction="*")]
        System.Threading.Tasks.Task<FissalWebForm.ServiceReference1.BuscarDNI_BResponse> BuscarDNI_BAsync(FissalWebForm.ServiceReference1.BuscarDNI_BRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class CredencialWS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string claveField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarAseguradosDocIdent", WrapperNamespace="http://www.sis.gob.pe/", IsWrapped=true)]
    public partial class BuscarAseguradosDocIdentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.sis.gob.pe/")]
        public FissalWebForm.ServiceReference1.CredencialWS CredencialWS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=0)]
        public string IdEess;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=1)]
        public string TipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=2)]
        public string Documento;
        
        public BuscarAseguradosDocIdentRequest() {
        }
        
        public BuscarAseguradosDocIdentRequest(FissalWebForm.ServiceReference1.CredencialWS CredencialWS, string IdEess, string TipoDoc, string Documento) {
            this.CredencialWS = CredencialWS;
            this.IdEess = IdEess;
            this.TipoDoc = TipoDoc;
            this.Documento = Documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarAseguradosDocIdentResponse", WrapperNamespace="http://www.sis.gob.pe/", IsWrapped=true)]
    public partial class BuscarAseguradosDocIdentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=0)]
        public string BuscarAseguradosDocIdentResult;
        
        public BuscarAseguradosDocIdentResponse() {
        }
        
        public BuscarAseguradosDocIdentResponse(string BuscarAseguradosDocIdentResult) {
            this.BuscarAseguradosDocIdentResult = BuscarAseguradosDocIdentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarDNI_B", WrapperNamespace="http://www.sis.gob.pe/", IsWrapped=true)]
    public partial class BuscarDNI_BRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.sis.gob.pe/")]
        public FissalWebForm.ServiceReference1.CredencialWS CredencialWS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=0)]
        public string DNI_Cliente;
        
        public BuscarDNI_BRequest() {
        }
        
        public BuscarDNI_BRequest(FissalWebForm.ServiceReference1.CredencialWS CredencialWS, string DNI_Cliente) {
            this.CredencialWS = CredencialWS;
            this.DNI_Cliente = DNI_Cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarDNI_BResponse", WrapperNamespace="http://www.sis.gob.pe/", IsWrapped=true)]
    public partial class BuscarDNI_BResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=0)]
        public string BuscarDNI_BResult;
        
        public BuscarDNI_BResponse() {
        }
        
        public BuscarDNI_BResponse(string BuscarDNI_BResult) {
            this.BuscarDNI_BResult = BuscarDNI_BResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface siswsSoapChannel : FissalWebForm.ServiceReference1.siswsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class siswsSoapClient : System.ServiceModel.ClientBase<FissalWebForm.ServiceReference1.siswsSoap>, FissalWebForm.ServiceReference1.siswsSoap {
        
        public siswsSoapClient() {
        }
        
        public siswsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public siswsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public siswsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public siswsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentResponse FissalWebForm.ServiceReference1.siswsSoap.BuscarAseguradosDocIdent(FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentRequest request) {
            return base.Channel.BuscarAseguradosDocIdent(request);
        }
        
        public string BuscarAseguradosDocIdent(FissalWebForm.ServiceReference1.CredencialWS CredencialWS, string IdEess, string TipoDoc, string Documento) {
            FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentRequest inValue = new FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentRequest();
            inValue.CredencialWS = CredencialWS;
            inValue.IdEess = IdEess;
            inValue.TipoDoc = TipoDoc;
            inValue.Documento = Documento;
            FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentResponse retVal = ((FissalWebForm.ServiceReference1.siswsSoap)(this)).BuscarAseguradosDocIdent(inValue);
            return retVal.BuscarAseguradosDocIdentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentResponse> FissalWebForm.ServiceReference1.siswsSoap.BuscarAseguradosDocIdentAsync(FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentRequest request) {
            return base.Channel.BuscarAseguradosDocIdentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentResponse> BuscarAseguradosDocIdentAsync(FissalWebForm.ServiceReference1.CredencialWS CredencialWS, string IdEess, string TipoDoc, string Documento) {
            FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentRequest inValue = new FissalWebForm.ServiceReference1.BuscarAseguradosDocIdentRequest();
            inValue.CredencialWS = CredencialWS;
            inValue.IdEess = IdEess;
            inValue.TipoDoc = TipoDoc;
            inValue.Documento = Documento;
            return ((FissalWebForm.ServiceReference1.siswsSoap)(this)).BuscarAseguradosDocIdentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FissalWebForm.ServiceReference1.BuscarDNI_BResponse FissalWebForm.ServiceReference1.siswsSoap.BuscarDNI_B(FissalWebForm.ServiceReference1.BuscarDNI_BRequest request) {
            return base.Channel.BuscarDNI_B(request);
        }
        
        public string BuscarDNI_B(FissalWebForm.ServiceReference1.CredencialWS CredencialWS, string DNI_Cliente) {
            FissalWebForm.ServiceReference1.BuscarDNI_BRequest inValue = new FissalWebForm.ServiceReference1.BuscarDNI_BRequest();
            inValue.CredencialWS = CredencialWS;
            inValue.DNI_Cliente = DNI_Cliente;
            FissalWebForm.ServiceReference1.BuscarDNI_BResponse retVal = ((FissalWebForm.ServiceReference1.siswsSoap)(this)).BuscarDNI_B(inValue);
            return retVal.BuscarDNI_BResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FissalWebForm.ServiceReference1.BuscarDNI_BResponse> FissalWebForm.ServiceReference1.siswsSoap.BuscarDNI_BAsync(FissalWebForm.ServiceReference1.BuscarDNI_BRequest request) {
            return base.Channel.BuscarDNI_BAsync(request);
        }
        
        public System.Threading.Tasks.Task<FissalWebForm.ServiceReference1.BuscarDNI_BResponse> BuscarDNI_BAsync(FissalWebForm.ServiceReference1.CredencialWS CredencialWS, string DNI_Cliente) {
            FissalWebForm.ServiceReference1.BuscarDNI_BRequest inValue = new FissalWebForm.ServiceReference1.BuscarDNI_BRequest();
            inValue.CredencialWS = CredencialWS;
            inValue.DNI_Cliente = DNI_Cliente;
            return ((FissalWebForm.ServiceReference1.siswsSoap)(this)).BuscarDNI_BAsync(inValue);
        }
    }
}
