//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalWinForm.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sis.gob.pe/", ConfigurationName="ServiceReference1.siswsSoap")]
    public interface siswsSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje BuscarAseguradosDocIdentRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAseguradosDocIdent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentResponse BuscarAseguradosDocIdent(FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAseguradosDocIdent", ReplyAction="*")]
        System.Threading.Tasks.Task<FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentResponse> BuscarAseguradosDocIdentAsync(FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class CredencialWS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string claveField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarAseguradosDocIdent", WrapperNamespace="http://www.sis.gob.pe/", IsWrapped=true)]
    public partial class BuscarAseguradosDocIdentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.sis.gob.pe/")]
        public FissalWinForm.ServiceReference1.CredencialWS CredencialWS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=0)]
        public string IdEess;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=1)]
        public string TipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=2)]
        public string Documento;
        
        public BuscarAseguradosDocIdentRequest() {
        }
        
        public BuscarAseguradosDocIdentRequest(FissalWinForm.ServiceReference1.CredencialWS CredencialWS, string IdEess, string TipoDoc, string Documento) {
            this.CredencialWS = CredencialWS;
            this.IdEess = IdEess;
            this.TipoDoc = TipoDoc;
            this.Documento = Documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarAseguradosDocIdentResponse", WrapperNamespace="http://www.sis.gob.pe/", IsWrapped=true)]
    public partial class BuscarAseguradosDocIdentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sis.gob.pe/", Order=0)]
        public string BuscarAseguradosDocIdentResult;
        
        public BuscarAseguradosDocIdentResponse() {
        }
        
        public BuscarAseguradosDocIdentResponse(string BuscarAseguradosDocIdentResult) {
            this.BuscarAseguradosDocIdentResult = BuscarAseguradosDocIdentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface siswsSoapChannel : FissalWinForm.ServiceReference1.siswsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class siswsSoapClient : System.ServiceModel.ClientBase<FissalWinForm.ServiceReference1.siswsSoap>, FissalWinForm.ServiceReference1.siswsSoap {
        
        public siswsSoapClient() {
        }
        
        public siswsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public siswsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public siswsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public siswsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentResponse FissalWinForm.ServiceReference1.siswsSoap.BuscarAseguradosDocIdent(FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentRequest request) {
            return base.Channel.BuscarAseguradosDocIdent(request);
        }
        
        public string BuscarAseguradosDocIdent(FissalWinForm.ServiceReference1.CredencialWS CredencialWS, string IdEess, string TipoDoc, string Documento) {
            FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentRequest inValue = new FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentRequest();
            inValue.CredencialWS = CredencialWS;
            inValue.IdEess = IdEess;
            inValue.TipoDoc = TipoDoc;
            inValue.Documento = Documento;
            FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentResponse retVal = ((FissalWinForm.ServiceReference1.siswsSoap)(this)).BuscarAseguradosDocIdent(inValue);
            return retVal.BuscarAseguradosDocIdentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentResponse> FissalWinForm.ServiceReference1.siswsSoap.BuscarAseguradosDocIdentAsync(FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentRequest request) {
            return base.Channel.BuscarAseguradosDocIdentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentResponse> BuscarAseguradosDocIdentAsync(FissalWinForm.ServiceReference1.CredencialWS CredencialWS, string IdEess, string TipoDoc, string Documento) {
            FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentRequest inValue = new FissalWinForm.ServiceReference1.BuscarAseguradosDocIdentRequest();
            inValue.CredencialWS = CredencialWS;
            inValue.IdEess = IdEess;
            inValue.TipoDoc = TipoDoc;
            inValue.Documento = Documento;
            return ((FissalWinForm.ServiceReference1.siswsSoap)(this)).BuscarAseguradosDocIdentAsync(inValue);
        }
    }
}
