//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public Actividad()
        {
            this.Finalidad = new HashSet<Finalidad>();
        }
    
        public string ActividadId { get; set; }
        public string DescripcionActividad { get; set; }
        public string ProductoId { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual ICollection<Finalidad> Finalidad { get; set; }
    }
}
