//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtencionCierre
    {
        public string Periodo { get; set; }
        public string Mes { get; set; }
        public string Observado { get; set; }
        public string Disa { get; set; }
        public string CodigoEESS { get; set; }
        public Nullable<int> Ejecutora { get; set; }
        public string Categoria { get; set; }
        public string Servicio { get; set; }
        public string Financiamiento { get; set; }
        public string Componente { get; set; }
        public string ModalidadAtencion { get; set; }
        public string FUA { get; set; }
        public string Contrato { get; set; }
        public int ate_idnumreg { get; set; }
        public string ate_tipdig { get; set; }
        public string ate_odsis { get; set; }
        public string ate_estado { get; set; }
        public string ate_aus { get; set; }
        public string ate_disa { get; set; }
        public string ate_autogenerado { get; set; }
        public Nullable<int> ate_edad { get; set; }
        public Nullable<System.DateTime> ate_fecatencion { get; set; }
        public string ate_appat { get; set; }
        public string ate_apmat { get; set; }
        public string ate_pnom { get; set; }
        public string ate_snom { get; set; }
        public Nullable<System.DateTime> ate_fecnac { get; set; }
        public string ate_idsexo { get; set; }
        public string ate_tipo_personal_salud { get; set; }
        public string Nivel { get; set; }
        public string ate_dni { get; set; }
        public string region { get; set; }
        public string ate_Fissal { get; set; }
        public string ate_FissalDiag { get; set; }
        public Nullable<decimal> ate_FissalValorNeto { get; set; }
        public Nullable<decimal> ate_FissalValorServ { get; set; }
        public Nullable<decimal> ate_FissalValorConsumo { get; set; }
        public Nullable<decimal> ate_FissalValorBruto { get; set; }
        public Nullable<decimal> ate_FissalValorNetoMed { get; set; }
        public Nullable<decimal> ate_FissalValorNetoIns { get; set; }
        public Nullable<decimal> ate_FissalValorNetoApo { get; set; }
        public string ate_fissalConvenio { get; set; }
        public string Diagnostico_FISSAL { get; set; }
        public string PeriodoTransferencia { get; set; }
        public string Rj { get; set; }
    }
}
