//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtencionCierre_Diagnosticos
    {
        public int IdNumRegAte { get; set; }
        public int IdNUmReg { get; set; }
        public int NumeroDiag { get; set; }
        public string Codigo { get; set; }
        public string TipoDiag { get; set; }
        public string DxIngEgr { get; set; }
        public string esFissal { get; set; }
        public string mesProd_dia { get; set; }
    }
}
