//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorizacionTranferencia
    {
        public int AutorizacionTranferenciaId { get; set; }
        public string PacienteId { get; set; }
        public int EstablecimientoId { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public string DocumentoAutorizacion { get; set; }
        public Nullable<System.DateTime> FechaTransferencias { get; set; }
        public string DocumentoTranferencia { get; set; }
        public string CategoriaId { get; set; }
        public byte EstadioId { get; set; }
        public string Fase { get; set; }
        public string Tipo { get; set; }
        public string Modalidad { get; set; }
        public decimal Monto { get; set; }
    }
}
