//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion
    {
        public Autorizacion()
        {
            this.AdicionalProcedimiento = new HashSet<AdicionalProcedimiento>();
            this.AdionalMedicamento = new HashSet<AdionalMedicamento>();
            this.MovimientoPacienteDetalle = new HashSet<MovimientoPacienteDetalle>();
        }
    
        public int AutorizacionId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public string CodigoAutorizacion { get; set; }
        public byte TipoAutorizacionId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public System.DateTime Vigencia { get; set; }
        public int EstablecimientoId { get; set; }
        public int TipoDocumentoId { get; set; }
        public string NumeroDocumento { get; set; }
        public string PacienteId { get; set; }
        public int TratamiendoId { get; set; }
        public int Version { get; set; }
        public string observacion { get; set; }
        public bool Adicional { get; set; }
        public string Modalidad { get; set; }
        public bool ControlaCantidad { get; set; }
        public bool DiagnosticoAsociado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaInformeMedico { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public string Tipo { get; set; }
        public bool Anulado { get; set; }
        public string Nro_Solicitud { get; set; }
        public bool Enviado { get; set; }
        public bool PreAutorizado { get; set; }
        public virtual ICollection<AdicionalProcedimiento> AdicionalProcedimiento { get; set; }
        public virtual ICollection<AdionalMedicamento> AdionalMedicamento { get; set; }
        public virtual ICollection<MovimientoPacienteDetalle> MovimientoPacienteDetalle { get; set; }
        public virtual TipoAutorizacion TipoAutorizacion { get; set; }
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
