//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaCIE
    {
        public CategoriaCIE()
        {
            this.SolicitudAutorizacion = new HashSet<SolicitudAutorizacion>();
            this.Enfermedad = new HashSet<Enfermedad>();
            this.EsquemaCategoria = new HashSet<EsquemaCategoria>();
            this.EsquemaEstablecimiento = new HashSet<EsquemaEstablecimiento>();
        }
    
        public string CategoriaId { get; set; }
        public string GrupoId { get; set; }
        public string Descripcion { get; set; }
        public bool cobertura { get; set; }
        public string FinalidadId { get; set; }
    
        public virtual ICollection<SolicitudAutorizacion> SolicitudAutorizacion { get; set; }
        public virtual Finalidad Finalidad { get; set; }
        public virtual ICollection<Enfermedad> Enfermedad { get; set; }
        public virtual ICollection<EsquemaCategoria> EsquemaCategoria { get; set; }
        public virtual ICollection<EsquemaEstablecimiento> EsquemaEstablecimiento { get; set; }
        public virtual GrupoCIE GrupoCIE { get; set; }
    }
}
