//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlMedicoLog
    {
        public long ControlMedicoLogId { get; set; }
        public long Fua { get; set; }
        public int TipoControlMedicoId { get; set; }
        public int TipoObservacionId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public int id_usuario { get; set; }
    }
}
