//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinoAsegurado
    {
        public DestinoAsegurado()
        {
            this.MovimientoPaciente = new HashSet<MovimientoPaciente>();
        }
    
        public byte DestinoAseguradoId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<MovimientoPaciente> MovimientoPaciente { get; set; }
    }
}
