//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISA
    {
        public DISA()
        {
            this.Red = new HashSet<Red>();
        }
    
        public short DisaId { get; set; }
        public string Descripcion { get; set; }
        public string SisId { get; set; }
    
        public virtual ICollection<Red> Red { get; set; }
    }
}
