//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enfermedad
    {
        public Enfermedad()
        {
            this.MovimientoPacienteDetalle = new HashSet<MovimientoPacienteDetalle>();
            this.MovimientoPacienteDetalle1 = new HashSet<MovimientoPacienteDetalle>();
        }
    
        public string EnfermedadId { get; set; }
        public string CategoriaId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual CategoriaCIE CategoriaCIE { get; set; }
        public virtual ICollection<MovimientoPacienteDetalle> MovimientoPacienteDetalle { get; set; }
        public virtual ICollection<MovimientoPacienteDetalle> MovimientoPacienteDetalle1 { get; set; }
    }
}
