//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsquemaCategoria
    {
        public short EsquemaId { get; set; }
        public string CategoriaId { get; set; }
        public byte EstadioId { get; set; }
        public bool habitual { get; set; }
        public bool opcional { get; set; }
        public bool alternativo { get; set; }
    
        public virtual CategoriaCIE CategoriaCIE { get; set; }
        public virtual Esquema Esquema { get; set; }
        public virtual Estadio Estadio { get; set; }
    }
}
