//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esquema
    {
        public Esquema()
        {
            this.EsquemaCategoria = new HashSet<EsquemaCategoria>();
            this.MovimientoMedicamento = new HashSet<MovimientoMedicamento>();
            this.TratamientoMedicamento = new HashSet<TratamientoMedicamento>();
        }
    
        public short EsquemaId { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<EsquemaCategoria> EsquemaCategoria { get; set; }
        public virtual ICollection<MovimientoMedicamento> MovimientoMedicamento { get; set; }
        public virtual ICollection<TratamientoMedicamento> TratamientoMedicamento { get; set; }
    }
}
