//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadio
    {
        public Estadio()
        {
            this.EsquemaCategoria = new HashSet<EsquemaCategoria>();
            this.Paquete = new HashSet<Paquete>();
        }
    
        public byte EstadioId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<EsquemaCategoria> EsquemaCategoria { get; set; }
        public virtual ICollection<Paquete> Paquete { get; set; }
    }
}
