//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoCuentaConciliacion
    {
        public int EstadoCuentaConciliacionId { get; set; }
        public int EstablecimientoId { get; set; }
        public string PacienteId { get; set; }
        public int CadenaId { get; set; }
        public string NoFallecido { get; set; }
        public string ActivoSis { get; set; }
        public string ActivoFissal { get; set; }
        public string Estado { get; set; }
        public int CodigoConciliacion { get; set; }
    }
}
