//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finalidad
    {
        public Finalidad()
        {
            this.CategoriaCIE = new HashSet<CategoriaCIE>();
        }
    
        public string FinalidadId { get; set; }
        public string DescripcionFinalidad { get; set; }
        public string ActividadId { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual ICollection<CategoriaCIE> CategoriaCIE { get; set; }
    }
}
