//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoCIE
    {
        public GrupoCIE()
        {
            this.CategoriaCIE = new HashSet<CategoriaCIE>();
        }
    
        public string GrupoId { get; set; }
        public string CapituloId { get; set; }
        public string Descripcion { get; set; }
        public string Rango { get; set; }
    
        public virtual CapituloCIE CapituloCIE { get; set; }
        public virtual ICollection<CategoriaCIE> CategoriaCIE { get; set; }
    }
}
