//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoMedicamento
    {
        public long Fua { get; set; }
        public int DetalleId { get; set; }
        public int MedicamentoId { get; set; }
        public int MedicamentoIdNuevo { get; set; }
        public short EsquemaId { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public int Prescrito { get; set; }
        public int Consumo { get; set; }
        public int Convenio { get; set; }
        public string obs { get; set; }
        public bool paquete { get; set; }
        public Nullable<bool> CMObs { get; set; }
        public Nullable<int> CMCantidadObservada { get; set; }
        public Nullable<int> CMTipoObservacionId { get; set; }
        public Nullable<bool> Valorizado { get; set; }
        public Nullable<decimal> Monto2 { get; set; }
        public string CMObsDesc { get; set; }
        public Nullable<int> CantidadPagadaSIS { get; set; }
        public virtual Esquema Esquema { get; set; }
        public virtual Medicamento Medicamento { get; set; }
        public virtual MovimientoPacienteDetalle MovimientoPacienteDetalle { get; set; }
    }
}
