//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoPacienteDetallex
    {
        public long Fua { get; set; }
        public int DetalleId { get; set; }
        public Nullable<int> AutorizacionId { get; set; }
        public string EnfermedadIngresoId { get; set; }
        public string TipoDiagnosticoIngresoId { get; set; }
        public Nullable<short> EstadioId { get; set; }
        public Nullable<int> FaseId { get; set; }
        public string EnfermedadEgresoId { get; set; }
        public string TipoDiagnosticoEgresoId { get; set; }
    }
}
