//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Autorizacion = new HashSet<Autorizacion>();
            this.MovimientoPaciente = new HashSet<MovimientoPaciente>();
            this.SolicitudAutorizacion = new HashSet<SolicitudAutorizacion>();
         
        }
    
        public string PacienteId { get; set; }
        public Nullable<byte> TipoDocumentoId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string OtrosNombres { get; set; }
        public string NumeroDocumento { get; set; }
        public byte TipoRegimenId { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public byte SexoId { get; set; }
        public string Historia { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> fecha_defuncion { get; set; }
        public Nullable<int> EstablecimientoIdOrigen { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Validado { get; set; }
        public string nro_contrato { get; set; }    
        public string Ubigeo_Residencia { get; set; }     
        public string Ubigeo_Adscripcion { get; set; }
       
        public virtual ICollection<Autorizacion> Autorizacion { get; set; }
        public virtual ICollection<MovimientoPaciente> MovimientoPaciente { get; set; }
        public virtual ICollection<SolicitudAutorizacion> SolicitudAutorizacion { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual TipoRegimen TipoRegimen { get; set; }
    }
}
