//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimiento
    {
        public Procedimiento()
        {
            this.AdicionalProcedimiento = new HashSet<AdicionalProcedimiento>();
            this.MovimientoProcedimiento = new HashSet<MovimientoProcedimiento>();
            this.TarifarioProcedimiento = new HashSet<TarifarioProcedimiento>();
            this.TratamientoProcedimiento = new HashSet<TratamientoProcedimiento>();
        }
    
        public int ProcedimientoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string GrupoId { get; set; }
        public string SubGrupoId { get; set; }
        public string SisId { get; set; }
        public string MinsaId { get; set; }
        public string InenId { get; set; }
    
        public virtual ICollection<AdicionalProcedimiento> AdicionalProcedimiento { get; set; }
        public virtual ICollection<MovimientoProcedimiento> MovimientoProcedimiento { get; set; }
        public virtual ICollection<TarifarioProcedimiento> TarifarioProcedimiento { get; set; }
        public virtual ICollection<TratamientoProcedimiento> TratamientoProcedimiento { get; set; }
    }
}
