//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionCierreDigitacion
    {
        public int CierreId { get; set; }
        public int EstablecimientoId { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public System.DateTime FechaCierreRegistro { get; set; }
        public string UsuarioCierre { get; set; }
        public Nullable<int> FuasCerradas { get; set; }
    }
}
