//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Actividad = new HashSet<Actividad>();
        }
    
        public string ProductoId { get; set; }
        public string DescripcionProducto { get; set; }
        public string ProgramaId { get; set; }
    
        public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual Programa Programa { get; set; }
    }
}
