//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produccion
    {
        public int ProduccionId { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaProduccion { get; set; }        
        public System.DateTime FechaInicio { get; set; }        
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public bool Cerrada { get; set; }
    }
}
