//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduccionEstablecimiento
    {
        public int ProduccionEstablecimientoId { get; set; }
        public int ProduccionId { get; set; }
        public int EstablecimientoId { get; set; }
        public int AtencionesProduccion { get; set; }
        public Nullable<System.DateTime> FechaValorizacion { get; set; }
        public bool Valorizada { get; set; }
        public Nullable<int> AtencionesValorizadas { get; set; }
        public Nullable<int> CodigoControlMedico { get; set; }
        public Nullable<System.DateTime> FechaInicioControlMedico { get; set; }
        public Nullable<System.DateTime> FechaFinControlMedico { get; set; }
        public string UsuarioIniciaControlMedico { get; set; }
        public Nullable<System.DateTime> FechaCierreControlMedico { get; set; }
        public string UsuarioCierraControlMedico { get; set; }
        public Nullable<int> AtencionesSupervisadas { get; set; }
        public bool Supervisada { get; set; }
        public string DocumentoControlMedico { get; set; }
        public Nullable<int> CodigoConciliacion { get; set; }
        public Nullable<System.DateTime> FechaInicioConciliacion { get; set; }
        public Nullable<System.DateTime> FechaFinConciliacion { get; set; }
        public string UsuarioIniciaConciliacion { get; set; }
        public Nullable<System.DateTime> FechaCierreConciliacion { get; set; }
        public string UsuarioCierraConciliacion { get; set; }
        public bool Conciliada { get; set; }
        public string DocumentoConciliacion { get; set; }
    }
}
