//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa
    {
        public Programa()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public string ProgramaId { get; set; }
        public string DescripcionPrograma { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
