//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAutorizacion
    {
        public SolicitudAutorizacion()
        {
            this.SolicitudAutorizacionMedicamento = new HashSet<SolicitudAutorizacionMedicamento>();
            this.SolicitudAutorizacionProcedimiento = new HashSet<SolicitudAutorizacionProcedimiento>();
        }
    
        public string Nro_Solicitud { get; set; }

        public System.DateTime Fecha_Solicitud { get; set; }
        public Nullable<bool> SoloRetrospectivo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public int DetalleId { get; set; }
        public int EstablecimientoId { get; set; }
        public string PacienteId { get; set; }
        public string NumeroDocumento { get; set; }
        public byte SexoId { get; set; }
        public Nullable<bool> ValidadoFISSAL { get; set; }
        public string Usuario_Solicitante { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<byte> TipoDocumentoId { get; set; }
        public string Descripcion { get; set; }
        public string Nombres { get; set; }
        public string OtrosNombres { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public byte TipoAutorizacionId_solicita { get; set; }
        public string EstadoAprobacion { get; set; }
        public string Observaciones { get; set; }
        public byte TipoAutorizacionId_aprueba { get; set; }
        public string UsuarioSolicita { get; set; }
        public string UsuarioAutoriza { get; set; }
        public string CodigoAutorizacion { get; set; }
        public System.DateTime FechaInicioSolicitada { get; set; }
        public Nullable<System.DateTime> FechaInicioAprobada { get; set; }
        public string CategoriaId { get; set; }
        public int EstadioId { get; set; }
        public int FaseId { get; set; }
        public Nullable<bool> enviado { get; set; }
        public Nullable<bool> recibido { get; set; }
        public bool Adicional { get; set; }
        public string Modalidad { get; set; }
        public bool ControlaCantidad { get; set; }
        public string ObservacionesFissal { get; set; }
        public Nullable<System.DateTime> FechaInformeMedico { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public string Tipo { get; set; }
        public byte Enviado { get; set; }
        public Nullable<System.DateTime> Fecha_Procesado { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public string Usuario_Procesa { get; set; }
        

        public int TipoAutorizacionId { get; set; }
        public int TratamientoId { get; set; }
        public int CadenaId { get; set; }
        public int Vigencia { get; set; }
        public DateTime Fecha_Aprobacion { get; set; }
        public string Tipo_MecaFinanc { get; set; }
        public int AutorizacionId { get; set; }

        public virtual CategoriaCIE CategoriaCIE { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual ICollection<SolicitudAutorizacionMedicamento> SolicitudAutorizacionMedicamento { get; set; }
        public virtual ICollection<SolicitudAutorizacionProcedimiento> SolicitudAutorizacionProcedimiento { get; set; }
        public virtual TipoAutorizacion TipoAutorizacion { get; set; }


        public bool ValidadoFissal { get; set; }
        public bool ValidadoSIS { get; set; }
        public Nullable<bool> ValidadoRENIEC { get; set; }
        public bool Asegurado { get; set; }
        public bool Activo { get; set; }
        
        public int TipoRegimenId { get; set; }
        public int Version { get; set; }
        
        public string Historia { get; set; }

        public Nullable<System.DateTime> Nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_defuncion { get; set; }
    }
}
