//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sugerencias
    {
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo { get; set; }
        public string TipoDocumentoIdentidad { get; set; }
        public string NroDocumentoIdentidad { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string EsAsegurado { get; set; }
        public string NoEspecifique { get; set; }
        public string NombreAsegurado { get; set; }
        public string Diagnostico { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public string Direccion { get; set; }
        public string Detalle { get; set; }
        public string Establecimiento { get; set; }
    }
}
