//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifario
    {
        public Tarifario()
        {
            this.TarifarioMedicamento = new HashSet<TarifarioMedicamento>();
            this.TarifarioProcedimiento = new HashSet<TarifarioProcedimiento>();
        }
    
        public int TarifarioId { get; set; }
        public int Version { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string EstadoEnvio { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual TarifarioResumen TarifarioResumen { get; set; }
        public virtual ICollection<TarifarioMedicamento> TarifarioMedicamento { get; set; }
        public virtual ICollection<TarifarioProcedimiento> TarifarioProcedimiento { get; set; }
    }
}
