//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifarioMedicamento
    {
        public int TarifarioId { get; set; }
        public int Version { get; set; }
        public int MedicamentoId { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Tarifario Tarifario { get; set; }
    }
}
