//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifarioResumen
    {
        public TarifarioResumen()
        {
            this.Tarifario = new HashSet<Tarifario>();
        }
    
        public int TarifarioId { get; set; }
        public int EstablecimientoId { get; set; }
        public Nullable<short> ultimaversion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual ICollection<Tarifario> Tarifario { get; set; }
    }
}
