//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoObservacion
    {
        public TipoObservacion()
        {
            this.ControlMedicoLog = new HashSet<ControlMedicoLog>();
        }
    
        public int TipoObservacionId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CategoriaObservacionId { get; set; }
    
        public virtual CategoriaObservacion CategoriaObservacion { get; set; }
        public virtual ICollection<ControlMedicoLog> ControlMedicoLog { get; set; }
    }
}
