//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAutorizacion
    {
        public TipoAutorizacion()
        {
            this.Autorizacion = new HashSet<Autorizacion>();
            this.Paquete = new HashSet<Paquete>();
            this.SolicitudAutorizacion = new HashSet<SolicitudAutorizacion>();
        }
    
        public byte TipoAutorizacionId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Autorizacion> Autorizacion { get; set; }
        public virtual ICollection<Paquete> Paquete { get; set; }
        public virtual ICollection<SolicitudAutorizacion> SolicitudAutorizacion { get; set; }
    }
}
