//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranferenciaFUAS
    {
        public int id { get; set; }
        public string Periodo { get; set; }
        public string Mes { get; set; }
        public Nullable<int> disa { get; set; }
        public string DisaDescripcion { get; set; }
        public Nullable<int> CodigoUnidadEjecutora { get; set; }
        public string UnidadEjecutoraDescripcion { get; set; }
        public string region { get; set; }
        public string CodigoEESS { get; set; }
        public string NombreEESS { get; set; }
        public string Categoria { get; set; }
        public string Servicio { get; set; }
        public string FUA { get; set; }
        public int idnumreg { get; set; }
        public Nullable<System.DateTime> fechaatencion { get; set; }
        public Nullable<decimal> Valor_Neto_FISSAL { get; set; }
        public Nullable<decimal> Valor_Servicio_FISSAL { get; set; }
        public Nullable<decimal> ValorConsumo_FISSAL { get; set; }
        public Nullable<decimal> Valor_Bruto_FISSAL { get; set; }
        public Nullable<decimal> ValorNeto_Medicamentos_FISSAL { get; set; }
        public Nullable<decimal> ValorNeto_Insumos_FISSAL { get; set; }
        public Nullable<decimal> ValorNeto_procedimientos_FISSAL { get; set; }
        public string Diagnostico { get; set; }
        public string DiagnosticoDescripcion { get; set; }
        public string ProgramaId { get; set; }
        public string DescripcionPrograma { get; set; }
        public string ProductoId { get; set; }
        public string DescripcionProducto { get; set; }
        public string ActividadId { get; set; }
        public string PeriodoTransferencia { get; set; }
        public string Rj { get; set; }
    }
}
