//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public Tratamiento()
        {
            this.TratamientoMedicamento = new HashSet<TratamientoMedicamento>();
            this.TratamientoProcedimiento = new HashSet<TratamientoProcedimiento>();
        }
    
        public int TratamientoId { get; set; }
        public int Version { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string EstadoEnvio { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<byte> TipoAutorizacionId { get; set; }
        public Nullable<bool> SoloRetrospectivo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Vigencia { get; set; }
        public Nullable<int> CadenaId { get; set; }


        public virtual Paquete Paquete { get; set; }
        public virtual ICollection<TratamientoMedicamento> TratamientoMedicamento { get; set; }
        public virtual ICollection<TratamientoProcedimiento> TratamientoProcedimiento { get; set; }
    }
}
