//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw2_SolicitudAutorizacionDetalle
    {
        public string Nro_Solicitud { get; set; }
        public int DetalleId { get; set; }
        public byte TipoAutorizacionId { get; set; }
        public int EstablecimientoId { get; set; }
        public string CategoriaId { get; set; }
        public byte EstadioId { get; set; }
        public int FaseId { get; set; }
        public int TratamientoId { get; set; }
        public byte Vigencia { get; set; }
        public short Version { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public string Modalidad { get; set; }
        public Nullable<bool> Adicional { get; set; }
        public Nullable<int> AutorizacionId { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public Nullable<System.DateTime> Fecha_Procesado { get; set; }
        public string Observaciones { get; set; }
        public string DescripcionTipoAutorizacion { get; set; }
        public string DescripcionEstablecimiento { get; set; }
        public string DescripcionCategoria { get; set; }
        public string DescripcionEstadio { get; set; }
        public string DescripcionFase { get; set; }
    }
}
