//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw2_SolicitudAutorizacion
    {
        public string Nro_Solicitud { get; set; }
        public int EstablecimientoId { get; set; }
        public string PacienteId { get; set; }
        public Nullable<byte> TipoDocumentoId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string OtrosNombres { get; set; }
        public string NumeroDocumento { get; set; }
        public byte TipoRegimenId { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public byte SexoId { get; set; }
        public string Historia { get; set; }
        public Nullable<System.DateTime> fecha_defuncion { get; set; }
        public Nullable<bool> Asegurado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.DateTime Fecha_Solicitud { get; set; }
        public string Usuario_Solicitante { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_Procesado { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public string Usuario_Procesa { get; set; }
        public Nullable<bool> ValidadoFISSAL { get; set; }
        public Nullable<bool> ValidadoSIS { get; set; }
        public Nullable<bool> ValidadoRENIEC { get; set; }
        public bool Enviado { get; set; }
        public Nullable<bool> Recibido { get; set; }
        public string DescripcionPaciente { get; set; }
        public string DescripcionEstablecimiento { get; set; }
        public string DescripcionTipoDocumento { get; set; }
        public string DescripcionTipoRegimen { get; set; }
        public string DescripcionSexo { get; set; }


        public int TipoAutorizacionId { get; set; }
        public int TratamientoId { get; set; }
    }
}
