//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Autorizaciones
    {
        public int AutorizacionId { get; set; }
        public string Estado { get; set; }
        public string CodigoAutorizacion { get; set; }
        public string Diagnostico { get; set; }
        public byte Estadio { get; set; }
        public int Fase { get; set; }
        public string Tipo { get; set; }
        public string Establecimiento { get; set; }
        public string ControlaCantidad { get; set; }
        public string Adicional { get; set; }
        public string DiagAsociado { get; set; }
        public System.DateTime Fecha { get; set; }
        public string PacienteId { get; set; }
        public string FaseDescripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime Vigencia { get; set; }
        public string observacion { get; set; }
        public int TratamiendoId { get; set; }
        public int Version { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Modalidad { get; set; }
    }
}
