//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Autorizacion
    {
        public string descripcionlarga { get; set; }
        public int AutorizacionId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public string CodigoAutorizacion { get; set; }
        public byte TipoAutorizacionId { get; set; }
        public string Descripcion { get; set; }
        public string PacienteId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string CategoriaId { get; set; }
        public string DescripcionDiagnostico { get; set; }
        public int FaseId { get; set; }
        public byte EstadioId { get; set; }
        public string DescripcionAutorizacion { get; set; }
        public int EstablecimientoId { get; set; }
        public int TratamiendoId { get; set; }
        public int Version { get; set; }
        public bool Adicional { get; set; }
        public string Modalidad { get; set; }
        public bool ControlaCantidad { get; set; }
        public string fasedescripcion { get; set; }
        public string pacientenombre { get; set; }
        public bool DiagnosticoAsociado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string observacion { get; set; }
        public string AutorizacionDescripcion { get; set; }
        public System.DateTime Vigencia { get; set; }
    }
}
