//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ControlMedicoLog
    {
        public long Fua { get; set; }
        public string TipoControlMedicoDescripcion { get; set; }
        public string TipoObservacionDescripcion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Login { get; set; }
    }
}
