//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EsquemasEstablecimiento
    {
        public short EsquemaId { get; set; }
        public int EstablecimientoId { get; set; }
        public string DescripcionEstablecimiento { get; set; }
        public string CategoriaId { get; set; }
        public string DescripcionCategoria { get; set; }
        public string Descripcion { get; set; }
        public Nullable<byte> EstadioId { get; set; }
        public bool habitual { get; set; }
        public bool opcional { get; set; }
        public bool alternativo { get; set; }
        public string descripcionlarga { get; set; }
    }
}
