//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EstablecimientoTodos
    {
        public int EstablecimientoId { get; set; }
        public string Descripcion { get; set; }
        public bool Convenio { get; set; }
        public bool Preliquidado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string SisId { get; set; }
        public Nullable<short> DisaId { get; set; }
        public string DisaDescripcion { get; set; }
        public Nullable<short> RedId { get; set; }
        public string RedDescripcion { get; set; }
        public Nullable<short> MicroRedId { get; set; }
        public string MicroRedDescripcion { get; set; }
        public string DepartamentoId { get; set; }
        public string ProvinciaId { get; set; }
        public string DistritoId { get; set; }
        public string DescripcionUbigeo { get; set; }
        public Nullable<short> UnidadEjecutoraId { get; set; }
        public Nullable<short> UbigeoId { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string RutaServidor { get; set; }
        public string UnidadEjecutoraDescripcion { get; set; }
    }
}
