//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_fuaprocedimiento
    {
        public long Fua { get; set; }
        public int EstablecimientoId { get; set; }
        public string PacienteId { get; set; }
        public int DetalleId { get; set; }
        public Nullable<int> AutorizacionId { get; set; }
        public int ProcedimientoId { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public int Prescrito { get; set; }
    }
}
