//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MovimientoPacienteDetalle
    {
        public long Fua { get; set; }
        public int DetalleId { get; set; }
        public Nullable<int> AutorizacionId { get; set; }
        public string EnfermedadIngresoId { get; set; }
        public string EnfermedadEgresoId { get; set; }
        public string descripciondiagnostico { get; set; }
        public string descripcionautorizacion { get; set; }
        public int TratamiendoId { get; set; }
        public int Version { get; set; }
        public string CodigoAutorizacion { get; set; }
        public string CategoriaId { get; set; }
        public string descripcionlarga { get; set; }
        public Nullable<short> EstadioId { get; set; }
        public Nullable<int> FaseId { get; set; }
        public string TipoDiagnosticoIngresoId { get; set; }
        public string TipoDiagnosticoEgresoId { get; set; }
        public bool DiagnosticoAsociado { get; set; }
        public string Lote { get; set; }
        public int EstablecimientoId { get; set; }
        public Nullable<bool> CMObs { get; set; }
        public Nullable<int> CMTipoObservacionId { get; set; }
        public string CMObsDesc { get; set; }
    }
}
