//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_medicamento
    {
        public string DigemidId { get; set; }
        public string DescripcionSiga { get; set; }
        public string Concentracion { get; set; }
        public string Presentacion { get; set; }
        public string Descripcion { get; set; }
        public int MedicamentoId { get; set; }
    }
}
