//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MovimientoPacienteFull
    {
        public long Fua { get; set; }
        public string anno { get; set; }
        public string correlativo { get; set; }
        public int EstablecimientoId { get; set; }
        public Nullable<byte> TipoIngresoId { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<byte> LugarAtencionId { get; set; }
        public string NumeroHistoria { get; set; }
        public int TipoPrestacionId { get; set; }
        public Nullable<byte> PersonalAtiendeId { get; set; }
        public string NumeroHojaRefiere { get; set; }
        public string EstablecimientoRefiereId { get; set; }
        public Nullable<byte> DestinoAseguradoId { get; set; }
        public string EstablecimientoContraRefiereId { get; set; }
        public string NumeroHojaContraRefiere { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string DNIResponsable { get; set; }
        public string Colegiatura { get; set; }
        public string NombresResponsable { get; set; }
        public string Especialidad { get; set; }
        public Nullable<byte> InstitucionId { get; set; }
        public string NumeroSeguro { get; set; }
        public Nullable<byte> ResponsableAtencionId { get; set; }
        public Nullable<bool> EstadoTransferencia { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string PacienteId { get; set; }
        public string login { get; set; }
        public Nullable<bool> enviado { get; set; }
        public Nullable<bool> recibido { get; set; }
        public Nullable<int> EstablecimientoRefiere { get; set; }
        public Nullable<int> EstablecimientoContraRefiere { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionPaciente { get; set; }
        public Nullable<byte> TipoDocumentoId { get; set; }
        public string DescripcionDocumento { get; set; }
        public byte TipoRegimenId { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public byte SexoId { get; set; }
        public string Historia { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> fecha_defuncion { get; set; }
        public string LugarAtencionDescripcion { get; set; }
        public string TipoPrestacionDescripcion { get; set; }
        public string TipoIngresoDescripcion { get; set; }
        public string PersonalAtiendeDescripcion { get; set; }
        public string InstitucionDescripcion { get; set; }
        public Nullable<bool> CMErrorResponsableAtencion { get; set; }
        public Nullable<bool> CMErrorFechaAtencion { get; set; }
        public Nullable<long> CMFuaReferencia { get; set; }
        public Nullable<bool> CMReconsiderado { get; set; }
        public Nullable<bool> CMObs { get; set; }
        public Nullable<bool> CM { get; set; }
        public Nullable<bool> CMPcpp { get; set; }
        public Nullable<decimal> MontoMedicamento { get; set; }
        public Nullable<decimal> MontoProcedimiento { get; set; }
        public Nullable<decimal> MontoFua { get; set; }
    }
}
