//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MovimientoPacienteValorizado
    {
        public long Fua { get; set; }
        public string correlativo { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string PacienteId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string descripcionestablecimiento { get; set; }
        public byte SexoId { get; set; }
        public string Historia { get; set; }
        public Nullable<System.DateTime> fecha_defuncion { get; set; }
        public bool Estado { get; set; }
        public string anno { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string login { get; set; }
        public int EstablecimientoId { get; set; }
    }
}
