//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_movimientoPacienteMedicamento
    {
        public long Fua { get; set; }
        public int DetalleId { get; set; }
        public int MedicamentoId { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public int Prescrito { get; set; }
        public int Consumo { get; set; }
        public int Convenio { get; set; }
        public string obs { get; set; }
        public string DescripcionSiga { get; set; }
        public short EsquemaId { get; set; }
        public bool paquete { get; set; }
        public string esquemadescripcion { get; set; }
        public string Lote { get; set; }
        public int EstablecimientoId { get; set; }
        public Nullable<int> CMTipoObservacionId { get; set; }
        public Nullable<int> CMCantidadObservada { get; set; }
        public Nullable<bool> CMObs { get; set; }
        public string CMObsDesc { get; set; }
        public Nullable<int> CantidadPagadaSIS { get; set; }
        public int AutorizacionId { get; set; }
        public string FechaAtencion { get; set; }
        public string DigemidId { get; set; }
    }
}
