//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PaqueteProcedimientos
    {
        public int TratamientoId { get; set; }
        public int ProcedimientoId { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public string Descripcion { get; set; }
        public int FaseId { get; set; }
        public byte EstadioId { get; set; }
        public string establecimientodescripcion { get; set; }
        public string diagnosticodescripcion { get; set; }
        public int EstablecimientoId { get; set; }
        public string fasedescripcion { get; set; }
        public string estadiodescripcion { get; set; }
        public string habitual { get; set; }
        public string opcional { get; set; }
        public string alternativo { get; set; }
        public string CategoriaId { get; set; }
        public Nullable<short> ultimaversion { get; set; }
        public int Version { get; set; }
        public string SisId { get; set; }
        public string InenId { get; set; }
    }
}
