//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PaqueteAutorizacion
    {
        public int TratamientoId { get; set; }
        public int version { get; set; }
        public int EstablecimientoId { get; set; }
        public byte EstadioId { get; set; }
        public int FaseId { get; set; }
        public string CategoriaId { get; set; }
        public string DescripcionLarga { get; set; }
    }
}
