//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_paquetes_imp
    {
        public string establecimientodescripcion { get; set; }
        public int EstablecimientoId { get; set; }
        public int version { get; set; }
        public string diagnosticodescripcion { get; set; }
        public string estadiodescripcion { get; set; }
        public string fasedescripcion { get; set; }
        public string esquemadescripcion { get; set; }
        public string tipo { get; set; }
        public int medicamentoid { get; set; }
        public string Descripcionsiga { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public Nullable<decimal> total { get; set; }
        public string CategoriaId { get; set; }
    }
}
