//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PrecioPeriodo
    {
        public string periodo { get; set; }
        public int EstablecimientoId { get; set; }
        public int ItemId { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string DescripcionSiga { get; set; }
        public string DigemidId { get; set; }
        public string DescripcionEstablecimiento { get; set; }
    }
}
