//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Paciente
    {
        public string PacienteId { get; set; }
        public Nullable<byte> TipoDocumentoId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public byte TipoRegimenId { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public string Historia { get; set; }
        public string tiporegimendescripcion { get; set; }
        public string Descripcion { get; set; }
        public string EstablecimientoDescripcion { get; set; }
    }
}
