//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PacienteBuscar
    {
        public string PacienteId { get; set; }
        public string Descripcion { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> fecha_defuncion { get; set; }
        public string establecimientoorigen { get; set; }
        public string NombreCompleto { get; set; }
    }
}
