//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReporteMovimientoMedicamento
    {
        public long Fua { get; set; }
        public int DetalleId { get; set; }
        public int MedicamentoId { get; set; }
        public short EsquemaId { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public int Prescrito { get; set; }
        public int Consumo { get; set; }
        public int Convenio { get; set; }
        public string obs { get; set; }
        public bool paquete { get; set; }
        public string EnfermedadId { get; set; }
        public string EnfermedadDescripcion { get; set; }
        public Nullable<short> EstadioId { get; set; }
        public Nullable<int> FaseId { get; set; }
        public string descripcionitem { get; set; }
        public Nullable<int> AutorizacionId { get; set; }
    }
}
