//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RptMovimientoMedicamento
    {
        public long Fua { get; set; }
        public string anno { get; set; }
        public string correlativo { get; set; }
        public int EstablecimientoId { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<short> EstadioId { get; set; }
        public Nullable<int> FaseId { get; set; }
        public int MedicamentoId { get; set; }
        public string Descripcion { get; set; }
        public int Prescrito { get; set; }
        public int Cantidad { get; set; }
        public bool paquete { get; set; }
        public string establecimiento { get; set; }
        public string PacienteId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public decimal Monto { get; set; }
    }
}
