//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SolicitudAutorizacion
    {
        public string Nro_Solicitud { get; set; }
        public string paciente { get; set; }
        public string TipoAutorizacionSolicitada { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public string EstadoAprobacion { get; set; }
        public string UsuarioSolicita { get; set; }
        public string UsuarioAutoriza { get; set; }
        public string CodigoAutorizacion { get; set; }
        public System.DateTime FechaInicioSolicitada { get; set; }
        public Nullable<System.DateTime> FechaInicioAprobada { get; set; }
        public byte EstadioId { get; set; }
        public int FaseId { get; set; }
        public bool Adicional { get; set; }
        public string Modalidad { get; set; }
        public bool ControlaCantidad { get; set; }
        public string TipoAutorizacionAprobada { get; set; }
        public int EstablecimientoId { get; set; }
        public string CategoriaId { get; set; }
        public string CategoriaDescripcion { get; set; }
        public string Tipo { get; set; }
        public string PacienteId { get; set; }
        public string DescripcionFase { get; set; }
        public string DescripcioEstadio { get; set; }


        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }

    }
}
