//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SolicitudAutorizacionProcedimiento
    {
        public string Nro_Solicitud { get; set; }
        public int ProcedimientoId { get; set; }
        public string Descripcion { get; set; }
        public int CantidadSolicitada { get; set; }
        public Nullable<decimal> PrecioSolicitado { get; set; }
        public Nullable<int> CantidadAprobada { get; set; }
        public Nullable<decimal> PrecioAprobado { get; set; }
        public string SisId { get; set; }
    }
}
