//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FissalBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ValorProcedimientos
    {
        public long Fua { get; set; }
        public int DetalleId { get; set; }
        public int ProcedimientoId { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public bool paquete { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public int AutorizacionId { get; set; }
        public string CodigoAutorizacion { get; set; }
    }
}
